### ISSUE TITLE
Review from F. Xavier Castellanos

### ISSUE THREAD

**Issue by nicholsn** [Brainhack-Proceedings-2015/clark_mx15_bids#2]
For the Craddock and Clark submission, I found it clear, concise, well-written. There were minor typos in the Results (functional neuroimaging was misspelled) and in Conclusions ("achieved" was misspelled as "acheived"), but they are of no consequence.

**Comment by pintohutch** [comment]
I could not find these misspellings. Maybe they were in an older revision? Or I could be missing something
